# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Build with restore
      run: msbuild /p:TargetFrameworkVersion=4.8.1
   
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_36922172
        password: ${{ secrets.ftp_password }}
        port: 21
        server_dir: ./htdocs/
    
