# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Build with restore
      run: msbuild /p:TargetFrameworkVersion=4.8.1
   
    - name: Push files
      uses: joutvhu/ftp-transfer@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_LOGIN }}
        password: ${{ secrets.FTP_PASSWORD }}
        commands: put ./ ./htdocs/
    
